<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.10deb1 setup script
 * Date: Fri, 27 May 2016 13:31:37 -0300
 */

/* Servers configuration */
$i = 0;

/* Server: mysql-cloneReader [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mysql-cloneReader';
$cfg['Servers'][$i]['host'] = '172.17.0.1';
$cfg['Servers'][$i]['port'] = 3307;
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '5748765c153d96.80712598';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
//$cfg['ForceSSL'] = true;
?>
